import { ChangeDetectionStrategy, Component, effect, inject, input, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { AdminApi, adminError } from './admin-api';
import { AdminOption } from './admin.models';
@Component({selector:'app-option-editor',imports:[ReactiveFormsModule],styleUrl:'./admin.scss',template:
`<section class="section"><h2>{{kind()==='materials'?'Materiales':'Extras'}}</h2><ul class="list">@for(o of options();track o.id){<li class="edit-box"><div class="actions"><strong>{{o.name}}</strong><span>Orden {{o.displayOrder}} · {{o.active?'Activo':'Inactivo'}}</span><button type="button" (click)="edit(o)" [disabled]="busy()">Editar</button></div></li>}@empty{<li class="muted">Todavía no hay opciones.</li>}</ul><form class="section" [formGroup]="form" (ngSubmit)="save()"><h3>{{id()?'Editar opción':'Agregar opción'}}</h3><div class="fields"><label>Nombre<input formControlName="name" maxlength="160" required></label><label>Orden<input formControlName="displayOrder" type="number" min="0" step="1" required></label><label class="check"><input type="checkbox" formControlName="active">Activo</label></div><p class="muted">Las opciones inactivas no aparecen en el catálogo público.</p>@if(error()){<p class="feedback error" role="alert">{{error()}}</p>}@if(message()){<p class="feedback" role="status">{{message()}}</p>}<div class="actions"><button class="primary" [disabled]="busy()||form.invalid">{{busy()?'Guardando…':id()?'Guardar opción':'Agregar opción'}}</button>@if(id()){<button type="button" (click)="edit()">Cancelar edición</button>}</div></form></section>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class OptionEditor {
 readonly productId=input.required<string>();readonly kind=input.required<'materials'|'extras'>();readonly initial=input.required<AdminOption[]>();readonly options=signal<AdminOption[]>([]);readonly id=signal<string|null>(null);readonly busy=signal(false);readonly error=signal('');readonly message=signal('');private readonly api=inject(AdminApi);
 readonly form=new FormGroup({name:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(160)]}),active:new FormControl(true,{nonNullable:true}),displayOrder:new FormControl(0,{nonNullable:true,validators:[Validators.required,Validators.min(0),Validators.pattern('^[0-9]+$')]})});
 constructor(){effect(()=>this.options.set(this.initial()));}
 edit(o?:AdminOption){this.id.set(o?.id??null);this.form.reset(o??{name:'',active:true,displayOrder:0});this.error.set('');this.message.set('');}
 save(){if(this.form.invalid||this.busy())return;this.busy.set(true);this.error.set('');this.api.saveOption(this.productId(),this.kind(),this.id(),this.form.getRawValue()).pipe(finalize(()=>this.busy.set(false))).subscribe({next:o=>{this.options.update(items=>[...items.filter(x=>x.id!==o.id),o].sort((a,b)=>a.displayOrder-b.displayOrder||a.id.localeCompare(b.id)));this.edit();this.message.set('Opción guardada.');},error:e=>this.error.set(adminError(e))});}
}
